---
- name: Create Webserver VMs
  hosts: localhost
  gather_facts: false
  vars:
    vm_name_prefix: "{{ webserver_vm_name }}"
    memory: "{{ webserver_vm_memory }}"
    number_of_vms: "{{ webserver_vm_count }}"
    vm_tag: "{{ webserver_vm_tag }}"
    vm_dns_domain: "{{ webserver_vm_dns_domain }}"
    is_stateless: True
  tasks:
  - import_tasks: create_ovirt_vms.yaml
