---
- name: Update Dnsmasq
  hosts: all
  gather_facts: false
  serial: 1
  tasks:
  - name: Obtain SSO token with using username/password credentials
    no_log: false
    ovirt_auth:
      url: "{{ lookup('env','OVIRT_URL') }}"
      username: "{{ lookup('env','OVIRT_USERNAME') }}"
      password: "{{ lookup('env','OVIRT_PASSWORD') }}"
      insecure: true
    delegate_to: localhost
    become: false
  - include: lab_dnsmasq_tasks.yaml vm_name="{{ hostvars[item]['name'] }}" 
    with_items:
      - "{{ groups['tag_lab_webserver'] }}"
      - "{{ groups['tag_lab_wordpress'] }}"
      - "{{ groups['tag_lab_jboss'] }}"
      - "{{ groups['tag_lab_tower'] }}"
